language: node_js
sudo: required
node_js:
    - "node"
addons:
  chrome: stable
script: npm run travis
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
